# Generated by Django 5.1.1 on 2024-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=128)),
                ('food_desc', models.CharField(max_length=1000)),
                ('food_price', models.IntegerField()),
            ],
        ),
    ]
